---
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      CLASSPATH: /etc/kafka/jars/*
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL  
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
          password.files="/etc/kafka/secrets/nermin.props,/etc/kafka/secrets/nejra.props,/etc/kafka/secrets/client.props";
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.nermindedovic.securitycbs.PasswordVerifier
    volumes:
      - ./security:/etc/kafka/secrets
      - ./target/security-cbs-1.0-SNAPSHOT.jar:/etc/kafka/jars/security-cbs-1.0-SNAPSHOT.jar




